<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageVersionOverrideEnabled>false</CentralPackageVersionOverrideEnabled>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Kentico.Xperience.Admin" Version="30.11.1" />
    <PackageVersion Include="Kentico.Xperience.ImageProcessing" Version="30.11.1" />
    <PackageVersion Include="Kentico.Xperience.WebApp" Version="30.11.1" />
  </ItemGroup>
</Project>